[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rpm-spec-editor"
version = "0.0.1"
description = "GUI editor and analyzer for RPM spec files"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

authors = [
    { name = "xewca" }
]

dependencies = [
    "PyQt5"
]

[project.scripts]
rpm-spec-editor = "rpm_spec_editor.app:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
rpm_spec_editor = ["assets/*.png"]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]

testpaths = [
    "tests"
]

addopts = """
-v
--tb=short
--strict-markers
"""

markers = [
    "unit",
    "integration",
    "system",
    "gui"
]

qt_api = "pyqt5"
